name: bmcs_env
channels:
- conda-forge
dependencies:
- appmode
- jupyter_contrib_nbextensions
- traits
- matplotlib-base
- numpy
- sympy
- ipywidgets
- ipympl
- pip:
  - https://github.com/kelidas/bmcs_utils
